---
- hosts: all
  remote_user: "{{ playbook_user }}"
  become: yes

  tasks:
  
  - name: apt update
    apt: 
      update_cache: yes

  - name: apt dist-upgrade
    apt: 
      upgrade: dist

  - name: apt autoremove
    apt:
      autoremove: yes

- hosts: storage
  remote_user: "{{ playbook_user }}"
  become: yes  

  tasks:

  - name: scrubbing pool
    command: zpool scrub {{ scrub_pool }}
    when: scrub_pool != ""
  
  - name: upgrading zpool
    command: zpool upgrade

  vars_prompt:
    - name: "scrub_pool"
      prompt: "For 'storage' servers, enter pool ID to scrub (blank to skip)"
      private: no

# Need better method for copying tons of config files besides rsync
# Copy container config files and databases from Docker host to Storage pool
# Takes too long, fails often
# - hosts: docker
#   become: yes

#   tasks:

#   - name: backing up local docker container directories
#     synchronize:
#       src: "{{ docker_container_source_dir }}"
#       dest: "{{ docker_container_backup_dir }}"
#       rsync_path: "sudo rsync"
#       archive: yes
#       recursive: yes
#     delegate_to: "{{ inventory_hostname }}"