---
- name: Install packages; nfs-common, nfs-kernel-server
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - nfs-common
      - nfs-kernel-server